'use strict';

/* Componenti v3: off-canvas, tendine, collapse, popover, tooltip e navbar. */

const LOGO = '<svg class="cat-logo" viewBox="0 0 120 40" role="img" aria-label="Logo"><rect width="120" height="40" rx="8" fill="currentColor" opacity="0.15"/><text x="60" y="26" text-anchor="middle" font-size="14" font-family="sans-serif" fill="currentColor">LOGO</text></svg>';
const LOGO_CSS = '.cat-logo { display: block; height: 2.25rem; width: auto; color: var(--cat-color-primary, #2f6f4e); }\n';

/* Off-canvas: stessa struttura per i quattro lati. Cambia solo la classe cat-offcanvas--start|end|top|bottom. */
function offcanvas(side, nome, descrizione, extra) {
  const id = 'cat-oc-' + side;
  const trasl = { start: 'translateX(-100%)', end: 'translateX(100%)', top: 'translateY(-100%)', bottom: 'translateY(100%)' }[side];
  const pos = {
    start: 'top: 0; bottom: 0; left: 0; width: min(20rem, 85vw);',
    end: 'top: 0; bottom: 0; right: 0; width: min(20rem, 85vw);',
    top: 'top: 0; left: 0; right: 0; height: min(18rem, 60vh);',
    bottom: 'bottom: 0; left: 0; right: 0; height: min(18rem, 60vh);'
  }[side];
  return {
    nome: nome,
    descrizione: descrizione,
    tag: ['offcanvas', 'pannello', side, 'aria'],
    html: `<button type="button" class="cat-oc-open" data-cat-offcanvas="#${id}">Apri il pannello</button>\n\n<div class="cat-offcanvas-backdrop" data-cat-offcanvas-backdrop hidden></div>\n<aside id="${id}" class="cat-offcanvas cat-offcanvas--${side}" role="dialog" aria-modal="true" aria-labelledby="${id}-title" tabindex="-1">\n  <header class="cat-offcanvas__head">\n    <h2 id="${id}-title">Titolo del pannello</h2>\n    <button type="button" class="cat-offcanvas__close" data-cat-offcanvas-close aria-label="Chiudi">×</button>\n  </header>\n  <div class="cat-offcanvas__body">\n${extra || '    <p>Contenuto del pannello: menu, filtri, carrello, dettagli.</p>'}\n  </div>\n</aside>\n`,
    css: `.cat-oc-open { padding: 0.55rem 1.2rem; border: 0; border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-primary, #2f6f4e); color: #fff; font: inherit; cursor: pointer; }\n\n.cat-offcanvas-backdrop { position: fixed; inset: 0; z-index: 1040; background: rgb(0 0 0 / 0.5); opacity: 0; transition: opacity 250ms ease; }\n.cat-offcanvas-backdrop.is-visible { opacity: 1; }\n\n.cat-offcanvas {\n  position: fixed;\n  ${pos}\n  z-index: 1050;\n  display: flex;\n  flex-direction: column;\n  background: var(--cat-color-surface, #fff);\n  color: var(--cat-color-text, #1c1c1a);\n  box-shadow: var(--cat-shadow-md, 0 4px 12px rgb(0 0 0 / 0.12));\n  transform: ${trasl};\n  visibility: hidden;\n  transition: transform 300ms ease, visibility 0s linear 300ms;\n}\n\n.cat-offcanvas.is-open { transform: none; visibility: visible; transition-delay: 0s; }\n.cat-offcanvas__head { display: flex; align-items: center; justify-content: space-between; padding: var(--cat-space-3, 1rem); border-bottom: 1px solid var(--cat-color-border, #d9d9d2); }\n.cat-offcanvas__head h2 { margin: 0; font-size: 1.25rem; }\n.cat-offcanvas__close { width: 2.25rem; height: 2.25rem; border: 0; border-radius: 50%; background: none; color: inherit; font-size: 1.5rem; line-height: 1; cursor: pointer; }\n.cat-offcanvas__body { flex: 1; padding: var(--cat-space-3, 1rem); overflow-y: auto; }\n.cat-offcanvas__body nav { display: grid; gap: 0.25rem; }\n.cat-offcanvas__body nav a { padding: 0.55rem 0.7rem; border-radius: var(--cat-radius-md, 0.5rem); color: inherit; text-decoration: none; }\n.cat-offcanvas__body nav a:hover { background: rgb(0 0 0 / 0.06); }\n\n@media (prefers-reduced-motion: reduce) {\n  .cat-offcanvas, .cat-offcanvas-backdrop { transition: none; }\n}\n`,
    js: `(function () {\n  var lastOpener = null;\n  function focusables(panel) {\n    return Array.prototype.slice.call(panel.querySelectorAll('a[href], button:not([disabled]), input, select, textarea, [tabindex]:not([tabindex="-1"])'));\n  }\n  function open(panel, opener) {\n    var backdrop = document.querySelector('[data-cat-offcanvas-backdrop]');\n    lastOpener = opener || null;\n    panel.classList.add('is-open');\n    if (backdrop) { backdrop.hidden = false; requestAnimationFrame(function () { backdrop.classList.add('is-visible'); }); }\n    document.body.style.overflow = 'hidden';\n    var f = focusables(panel);\n    (f[0] || panel).focus();\n  }\n  function close(panel) {\n    var backdrop = document.querySelector('[data-cat-offcanvas-backdrop]');\n    panel.classList.remove('is-open');\n    if (backdrop) { backdrop.classList.remove('is-visible'); setTimeout(function () { backdrop.hidden = true; }, 250); }\n    document.body.style.overflow = '';\n    if (lastOpener) lastOpener.focus();\n  }\n  document.querySelectorAll('[data-cat-offcanvas]').forEach(function (btn) {\n    var panel = document.querySelector(btn.getAttribute('data-cat-offcanvas'));\n    if (!panel) return;\n    btn.addEventListener('click', function () { open(panel, btn); });\n    panel.querySelectorAll('[data-cat-offcanvas-close]').forEach(function (c) { c.addEventListener('click', function () { close(panel); }); });\n    document.querySelectorAll('[data-cat-offcanvas-backdrop]').forEach(function (b) { b.addEventListener('click', function () { close(panel); }); });\n    panel.addEventListener('keydown', function (e) {\n      if (e.key === 'Escape') { close(panel); return; }\n      if (e.key !== 'Tab') return;\n      var f = focusables(panel);\n      if (!f.length) return;\n      var first = f[0], last = f[f.length - 1];\n      if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); }\n      else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); }\n    });\n  });\n})();\n`
  };
}

const MENU_LINKS = '    <nav aria-label="Menu">\n      <a href="#">Home</a>\n      <a href="#">Servizi</a>\n      <a href="#">Portfolio</a>\n      <a href="#">Contatti</a>\n    </nav>';

module.exports = [
  offcanvas('start', 'Off-canvas da sinistra', 'Pannello laterale che scorre da sinistra, con sfondo scuro, Esc, focus intrappolato e ritorno del focus', MENU_LINKS),
  offcanvas('end', 'Off-canvas da destra', 'Pannello laterale da destra: carrello, filtri o dettagli'),
  offcanvas('top', 'Off-canvas dall\'alto', 'Pannello a scomparsa dall\'alto: avvisi, ricerca estesa'),
  offcanvas('bottom', 'Off-canvas dal basso', 'Pannello dal basso: azioni, condivisione (versione desktop del bottom sheet)'),
  {
    nome: 'Collapse (mostra/nascondi)',
    descrizione: 'Pannello che si apre con animazione fluida dell\'altezza (grid 0fr → 1fr), senza calcoli in JS',
    tag: ['collapse', 'tendina', 'aria'],
    html: `<button type="button" class="cat-collapse-btn" aria-expanded="false" aria-controls="cat-collapse-1">Mostra dettagli</button>\n<div id="cat-collapse-1" class="cat-collapse">\n  <div class="cat-collapse__inner">\n    <p>Contenuto che compare e scompare. L'altezza si anima da sola.</p>\n  </div>\n</div>\n`,
    css: `.cat-collapse-btn { padding: 0.5rem 1rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-surface, #fff); color: inherit; font: inherit; cursor: pointer; }\n.cat-collapse { display: grid; grid-template-rows: 0fr; transition: grid-template-rows 300ms ease; }\n.cat-collapse.is-open { grid-template-rows: 1fr; }\n.cat-collapse__inner { overflow: hidden; }\n.cat-collapse__inner > :first-child { margin-top: var(--cat-space-2, 0.5rem); }\n@media (prefers-reduced-motion: reduce) { .cat-collapse { transition: none; } }\n`,
    js: `document.querySelectorAll('.cat-collapse-btn').forEach(function (btn) {\n  var panel = document.getElementById(btn.getAttribute('aria-controls'));\n  btn.addEventListener('click', function () {\n    var open = btn.getAttribute('aria-expanded') !== 'true';\n    btn.setAttribute('aria-expanded', String(open));\n    panel.classList.toggle('is-open', open);\n  });\n});\n`
  },
  {
    nome: 'Tendina con icone e separatori',
    descrizione: 'Menu a tendina con frecce su/giù, Home/End, Esc e chiusura al clic fuori',
    tag: ['dropdown', 'tendina', 'menu', 'aria'],
    html: `<div class="cat-dd" data-cat-dd>\n  <button type="button" class="cat-dd__btn" aria-haspopup="menu" aria-expanded="false">Account ▾</button>\n  <ul class="cat-dd__menu" role="menu" hidden>\n    <li role="none"><a role="menuitem" href="#">👤 Profilo</a></li>\n    <li role="none"><a role="menuitem" href="#">⚙️ Impostazioni</a></li>\n    <li role="separator" class="cat-dd__sep"></li>\n    <li role="none"><a role="menuitem" href="#">🚪 Esci</a></li>\n  </ul>\n</div>\n`,
    css: `.cat-dd { position: relative; display: inline-block; }\n.cat-dd__btn { padding: 0.5rem 1rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-surface, #fff); color: inherit; font: inherit; cursor: pointer; }\n.cat-dd__menu { position: absolute; left: 0; top: calc(100% + 4px); z-index: 20; min-width: 12rem; margin: 0; padding: 0.25rem; list-style: none; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-surface, #fff); box-shadow: var(--cat-shadow-md, 0 4px 12px rgb(0 0 0 / 0.12)); }\n.cat-dd__menu a { display: block; padding: 0.5rem 0.75rem; border-radius: var(--cat-radius-sm, 0.25rem); color: inherit; text-decoration: none; }\n.cat-dd__menu a:hover, .cat-dd__menu a:focus-visible { outline: 0; background: rgb(0 0 0 / 0.07); }\n.cat-dd__sep { height: 1px; margin: 0.25rem 0; background: var(--cat-color-border, #d9d9d2); }\n`,
    js: `document.querySelectorAll('[data-cat-dd]').forEach(function (root) {\n  var btn = root.querySelector('.cat-dd__btn');\n  var menu = root.querySelector('.cat-dd__menu');\n  var items = function () { return Array.prototype.slice.call(menu.querySelectorAll('[role="menuitem"]')); };\n  function set(open, focusFirst) {\n    btn.setAttribute('aria-expanded', String(open));\n    menu.hidden = !open;\n    if (open && focusFirst) items()[0].focus();\n  }\n  btn.addEventListener('click', function () { set(menu.hidden, false); });\n  btn.addEventListener('keydown', function (e) { if (e.key === 'ArrowDown') { e.preventDefault(); set(true, true); } });\n  menu.addEventListener('keydown', function (e) {\n    var list = items();\n    var i = list.indexOf(document.activeElement);\n    if (e.key === 'ArrowDown') { e.preventDefault(); list[(i + 1) % list.length].focus(); }\n    else if (e.key === 'ArrowUp') { e.preventDefault(); list[(i - 1 + list.length) % list.length].focus(); }\n    else if (e.key === 'Home') { e.preventDefault(); list[0].focus(); }\n    else if (e.key === 'End') { e.preventDefault(); list[list.length - 1].focus(); }\n    else if (e.key === 'Escape') { set(false); btn.focus(); }\n  });\n  document.addEventListener('click', function (e) { if (!root.contains(e.target)) set(false); });\n});\n`
  },
  {
    nome: 'Pulsante diviso con tendina (split)',
    descrizione: 'Azione principale a sinistra e freccia che apre le alternative, allineate a destra',
    tag: ['dropdown', 'tendina', 'pulsante'],
    html: `<div class="cat-split" data-cat-split>\n  <button type="button" class="cat-split__main">Salva</button>\n  <button type="button" class="cat-split__toggle" aria-haspopup="menu" aria-expanded="false" aria-label="Altre opzioni">▾</button>\n  <ul class="cat-split__menu" hidden>\n    <li><a href="#">Salva come bozza</a></li>\n    <li><a href="#">Salva e chiudi</a></li>\n    <li><a href="#">Salva una copia</a></li>\n  </ul>\n</div>\n`,
    css: `.cat-split { position: relative; display: inline-flex; }\n.cat-split button { padding: 0.55rem 1rem; border: 0; background: var(--cat-color-primary, #2f6f4e); color: #fff; font: inherit; cursor: pointer; }\n.cat-split__main { border-radius: var(--cat-radius-md, 0.5rem) 0 0 var(--cat-radius-md, 0.5rem); }\n.cat-split__toggle { border-left: 1px solid rgb(255 255 255 / 0.4) !important; border-radius: 0 var(--cat-radius-md, 0.5rem) var(--cat-radius-md, 0.5rem) 0; padding-inline: 0.7rem !important; }\n.cat-split__menu { position: absolute; right: 0; top: calc(100% + 4px); z-index: 20; min-width: 12rem; margin: 0; padding: 0.25rem; list-style: none; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-surface, #fff); box-shadow: var(--cat-shadow-md, 0 4px 12px rgb(0 0 0 / 0.12)); }\n.cat-split__menu a { display: block; padding: 0.5rem 0.75rem; border-radius: var(--cat-radius-sm, 0.25rem); color: inherit; text-decoration: none; }\n.cat-split__menu a:hover { background: rgb(0 0 0 / 0.07); }\n`,
    js: `document.querySelectorAll('[data-cat-split]').forEach(function (root) {\n  var t = root.querySelector('.cat-split__toggle');\n  var m = root.querySelector('.cat-split__menu');\n  function set(o) { t.setAttribute('aria-expanded', String(o)); m.hidden = !o; }\n  t.addEventListener('click', function () { set(m.hidden); });\n  document.addEventListener('click', function (e) { if (!root.contains(e.target)) set(false); });\n  root.addEventListener('keydown', function (e) { if (e.key === 'Escape') { set(false); t.focus(); } });\n});\n`
  },
  {
    nome: 'Mega menu a colonne',
    descrizione: 'Tendina larga con più colonne di link e un riquadro in evidenza',
    tag: ['mega-menu', 'tendina', 'navbar'],
    html: `<nav class="cat-mega" aria-label="Principale">\n  <button type="button" class="cat-mega__btn" aria-expanded="false" aria-controls="cat-mega-panel">Prodotti ▾</button>\n  <div id="cat-mega-panel" class="cat-mega__panel" hidden>\n    <div><h3>Categoria uno</h3><a href="#">Voce A</a><a href="#">Voce B</a><a href="#">Voce C</a></div>\n    <div><h3>Categoria due</h3><a href="#">Voce D</a><a href="#">Voce E</a><a href="#">Voce F</a></div>\n    <div class="cat-mega__feature"><h3>In evidenza</h3><p>Descrizione breve della novità.</p><a href="#">Scopri →</a></div>\n  </div>\n</nav>\n`,
    css: `.cat-mega { position: relative; }\n.cat-mega__btn { padding: 0.55rem 1rem; border: 0; background: none; color: inherit; font: inherit; cursor: pointer; }\n.cat-mega__panel { position: absolute; left: 0; top: 100%; z-index: 30; display: grid; grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr)); gap: var(--cat-space-4, 1.5rem); width: min(44rem, 92vw); padding: var(--cat-space-4, 1.5rem); border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-lg, 0.75rem); background: var(--cat-color-surface, #fff); box-shadow: var(--cat-shadow-md, 0 4px 12px rgb(0 0 0 / 0.12)); }\n.cat-mega__panel h3 { margin: 0 0 0.5rem; font-size: 0.8125rem; text-transform: uppercase; letter-spacing: 0.06em; color: var(--cat-color-text-muted, #5c5c57); }\n.cat-mega__panel a { display: block; padding: 0.25rem 0; color: inherit; text-decoration: none; }\n.cat-mega__panel a:hover { text-decoration: underline; }\n.cat-mega__feature { padding: var(--cat-space-3, 1rem); border-radius: var(--cat-radius-md, 0.5rem); background: rgb(47 111 78 / 0.1); }\n`,
    js: `document.querySelectorAll('.cat-mega').forEach(function (root) {\n  var btn = root.querySelector('.cat-mega__btn');\n  var panel = root.querySelector('.cat-mega__panel');\n  function set(o) { btn.setAttribute('aria-expanded', String(o)); panel.hidden = !o; }\n  btn.addEventListener('click', function () { set(panel.hidden); });\n  document.addEventListener('click', function (e) { if (!root.contains(e.target)) set(false); });\n  root.addEventListener('keydown', function (e) { if (e.key === 'Escape') { set(false); btn.focus(); } });\n});\n`
  },
  {
    nome: 'Select personalizzata',
    descrizione: 'Elenco a discesa stilizzabile (listbox accessibile) con tastiera',
    tag: ['select', 'tendina', 'form', 'aria'],
    html: `<div class="cat-select" data-cat-select>\n  <span id="cat-sel-label" class="cat-select__label">Città</span>\n  <button type="button" class="cat-select__btn" aria-haspopup="listbox" aria-expanded="false" aria-labelledby="cat-sel-label cat-sel-value"><span id="cat-sel-value">Torino</span> ▾</button>\n  <ul class="cat-select__list" role="listbox" aria-labelledby="cat-sel-label" tabindex="-1" hidden>\n    <li role="option" aria-selected="true">Torino</li>\n    <li role="option" aria-selected="false">Milano</li>\n    <li role="option" aria-selected="false">Roma</li>\n    <li role="option" aria-selected="false">Napoli</li>\n  </ul>\n</div>\n`,
    css: `.cat-select { position: relative; display: inline-grid; gap: 0.25rem; min-width: 12rem; }\n.cat-select__label { font-weight: 600; font-size: 0.9375rem; }\n.cat-select__btn { display: flex; justify-content: space-between; padding: 0.55rem 0.8rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-surface, #fff); color: inherit; font: inherit; text-align: left; cursor: pointer; }\n.cat-select__list { position: absolute; left: 0; right: 0; top: 100%; z-index: 20; margin: 4px 0 0; padding: 0.25rem; list-style: none; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-surface, #fff); box-shadow: var(--cat-shadow-md, 0 4px 12px rgb(0 0 0 / 0.12)); }\n.cat-select__list li { padding: 0.45rem 0.7rem; border-radius: var(--cat-radius-sm, 0.25rem); cursor: pointer; }\n.cat-select__list li:hover, .cat-select__list li.is-active { background: rgb(0 0 0 / 0.07); }\n.cat-select__list li[aria-selected="true"] { font-weight: 700; color: var(--cat-color-primary, #2f6f4e); }\n`,
    js: `document.querySelectorAll('[data-cat-select]').forEach(function (root) {\n  var btn = root.querySelector('.cat-select__btn');\n  var list = root.querySelector('.cat-select__list');\n  var out = btn.querySelector('span');\n  var opts = Array.prototype.slice.call(list.querySelectorAll('[role="option"]'));\n  var active = 0;\n  function mark(i) {\n    active = (i + opts.length) % opts.length;\n    opts.forEach(function (o, k) { o.classList.toggle('is-active', k === active); });\n  }\n  function set(open) {\n    btn.setAttribute('aria-expanded', String(open));\n    list.hidden = !open;\n    if (open) { mark(opts.findIndex(function (o) { return o.getAttribute('aria-selected') === 'true'; })); list.focus(); }\n  }\n  function choose(i) {\n    opts.forEach(function (o, k) { o.setAttribute('aria-selected', String(k === i)); });\n    out.textContent = opts[i].textContent;\n    set(false);\n    btn.focus();\n  }\n  btn.addEventListener('click', function () { set(list.hidden); });\n  opts.forEach(function (o, i) { o.addEventListener('click', function () { choose(i); }); });\n  list.addEventListener('keydown', function (e) {\n    if (e.key === 'ArrowDown') { e.preventDefault(); mark(active + 1); }\n    else if (e.key === 'ArrowUp') { e.preventDefault(); mark(active - 1); }\n    else if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); choose(active); }\n    else if (e.key === 'Escape') { set(false); btn.focus(); }\n  });\n  document.addEventListener('click', function (e) { if (!root.contains(e.target)) set(false); });\n});\n`
  },
  {
    nome: 'Menu contestuale (tasto destro)',
    descrizione: 'Menu che compare dove clicchi con il tasto destro nel riquadro',
    tag: ['menu', 'contestuale'],
    html: `<div class="cat-ctx-area" id="cat-ctx-area" tabindex="0">Clicca qui con il tasto destro</div>\n<ul class="cat-ctx" id="cat-ctx" role="menu" hidden>\n  <li role="none"><button role="menuitem" type="button">Copia</button></li>\n  <li role="none"><button role="menuitem" type="button">Incolla</button></li>\n  <li role="none"><button role="menuitem" type="button">Elimina</button></li>\n</ul>\n`,
    css: `.cat-ctx-area { display: grid; place-items: center; height: 9rem; border: 2px dashed var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-lg, 0.75rem); color: var(--cat-color-text-muted, #5c5c57); }\n.cat-ctx { position: fixed; z-index: 50; min-width: 10rem; margin: 0; padding: 0.25rem; list-style: none; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-surface, #fff); box-shadow: var(--cat-shadow-md, 0 4px 12px rgb(0 0 0 / 0.12)); }\n.cat-ctx button { display: block; width: 100%; padding: 0.45rem 0.7rem; border: 0; border-radius: var(--cat-radius-sm, 0.25rem); background: none; color: inherit; font: inherit; text-align: left; cursor: pointer; }\n.cat-ctx button:hover, .cat-ctx button:focus-visible { background: rgb(0 0 0 / 0.07); outline: 0; }\n`,
    js: `var area = document.getElementById('cat-ctx-area');\nvar menu = document.getElementById('cat-ctx');\narea.addEventListener('contextmenu', function (e) {\n  e.preventDefault();\n  menu.hidden = false;\n  menu.style.left = Math.min(e.clientX, window.innerWidth - menu.offsetWidth - 8) + 'px';\n  menu.style.top = Math.min(e.clientY, window.innerHeight - menu.offsetHeight - 8) + 'px';\n  menu.querySelector('button').focus();\n});\ndocument.addEventListener('click', function () { menu.hidden = true; });\ndocument.addEventListener('keydown', function (e) { if (e.key === 'Escape') menu.hidden = true; });\n`
  },
  {
    nome: 'Popover (riquadro al clic)',
    descrizione: 'Piccolo riquadro con titolo e testo ancorato a un pulsante',
    tag: ['popover', 'aria'],
    html: `<span class="cat-pop" data-cat-pop>\n  <button type="button" class="cat-pop__btn" aria-expanded="false" aria-controls="cat-pop-1">Info</button>\n  <div id="cat-pop-1" class="cat-pop__box" role="dialog" aria-label="Informazioni" hidden>\n    <strong>Titolo</strong>\n    <p>Spiegazione breve, più lunga di un tooltip.</p>\n  </div>\n</span>\n`,
    css: `.cat-pop { position: relative; display: inline-block; }\n.cat-pop__btn { padding: 0.45rem 1rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-surface, #fff); color: inherit; font: inherit; cursor: pointer; }\n.cat-pop__box { position: absolute; left: 50%; bottom: calc(100% + 10px); z-index: 20; width: 15rem; padding: 0.75rem 1rem; transform: translateX(-50%); border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-surface, #fff); box-shadow: var(--cat-shadow-md, 0 4px 12px rgb(0 0 0 / 0.12)); }\n.cat-pop__box::after { content: ""; position: absolute; left: 50%; top: 100%; width: 10px; height: 10px; margin: -5px 0 0 -5px; transform: rotate(45deg); border-right: 1px solid var(--cat-color-border, #d9d9d2); border-bottom: 1px solid var(--cat-color-border, #d9d9d2); background: var(--cat-color-surface, #fff); }\n.cat-pop__box p { margin: 0.25rem 0 0; }\n`,
    js: `document.querySelectorAll('[data-cat-pop]').forEach(function (root) {\n  var btn = root.querySelector('.cat-pop__btn');\n  var box = root.querySelector('.cat-pop__box');\n  function set(o) { btn.setAttribute('aria-expanded', String(o)); box.hidden = !o; }\n  btn.addEventListener('click', function () { set(box.hidden); });\n  document.addEventListener('click', function (e) { if (!root.contains(e.target)) set(false); });\n  root.addEventListener('keydown', function (e) { if (e.key === 'Escape') { set(false); btn.focus(); } });\n});\n`
  },
  {
    nome: 'Tooltip nelle quattro direzioni',
    descrizione: 'Suggerimenti solo CSS sopra, sotto, a sinistra e a destra, anche al focus',
    tag: ['tooltip', 'senza-js'],
    html: `<div class="cat-tips">\n  <button type="button" class="cat-tip2" data-tip="Sopra" data-pos="top">Sopra</button>\n  <button type="button" class="cat-tip2" data-tip="Sotto" data-pos="bottom">Sotto</button>\n  <button type="button" class="cat-tip2" data-tip="A sinistra" data-pos="left">Sinistra</button>\n  <button type="button" class="cat-tip2" data-tip="A destra" data-pos="right">Destra</button>\n</div>\n`,
    css: `.cat-tips { display: flex; flex-wrap: wrap; gap: 2.5rem; padding: 2.5rem 5rem; }\n.cat-tip2 { position: relative; padding: 0.45rem 1rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-surface, #fff); color: inherit; font: inherit; cursor: pointer; }\n.cat-tip2::after { content: attr(data-tip); position: absolute; padding: 0.25rem 0.6rem; border-radius: var(--cat-radius-sm, 0.25rem); background: #1c1c1a; color: #fff; font-size: 0.8125rem; white-space: nowrap; opacity: 0; pointer-events: none; transition: opacity 150ms ease; z-index: 10; }\n.cat-tip2:hover::after, .cat-tip2:focus-visible::after { opacity: 1; }\n.cat-tip2[data-pos="top"]::after { bottom: calc(100% + 6px); left: 50%; transform: translateX(-50%); }\n.cat-tip2[data-pos="bottom"]::after { top: calc(100% + 6px); left: 50%; transform: translateX(-50%); }\n.cat-tip2[data-pos="left"]::after { right: calc(100% + 6px); top: 50%; transform: translateY(-50%); }\n.cat-tip2[data-pos="right"]::after { left: calc(100% + 6px); top: 50%; transform: translateY(-50%); }\n@media (prefers-reduced-motion: reduce) { .cat-tip2::after { transition: none; } }\n`,
    js: ''
  },

  /* ---------- navbar ---------- */
  {
    nome: 'Navbar con ricerca e menu utente',
    descrizione: 'Logo, link, campo di ricerca e tendina dell\'account; si dispone su due righe su schermo stretto',
    tag: ['navbar', 'logo', 'ricerca', 'dropdown'],
    html: `<header class="cat-nav2">\n  <a href="/" class="cat-nav2__brand" aria-label="Home">${LOGO}</a>\n  <nav class="cat-nav2__links" aria-label="Principale"><a href="#" aria-current="page">Home</a><a href="#">Catalogo</a><a href="#">Novità</a></nav>\n  <form role="search" class="cat-nav2__search"><input type="search" placeholder="Cerca…" aria-label="Cerca"></form>\n  <div class="cat-nav2__user" data-cat-nav-user>\n    <button type="button" aria-expanded="false" aria-haspopup="menu" aria-label="Menu account">MR</button>\n    <ul hidden><li><a href="#">Profilo</a></li><li><a href="#">Ordini</a></li><li><a href="#">Esci</a></li></ul>\n  </div>\n</header>\n`,
    css: `${LOGO_CSS}\n.cat-nav2 { display: flex; flex-wrap: wrap; align-items: center; gap: var(--cat-space-2, 0.5rem) var(--cat-space-3, 1rem); padding: var(--cat-space-2, 0.5rem) var(--cat-space-3, 1rem); border-bottom: 1px solid var(--cat-color-border, #d9d9d2); background: var(--cat-color-surface, #fff); }\n.cat-nav2__links { display: flex; gap: var(--cat-space-3, 1rem); }\n.cat-nav2__links a { color: inherit; text-decoration: none; padding-bottom: 2px; border-bottom: 2px solid transparent; }\n.cat-nav2__links a[aria-current="page"], .cat-nav2__links a:hover { border-bottom-color: var(--cat-color-primary, #2f6f4e); }\n.cat-nav2__search { flex: 1 1 12rem; margin-left: auto; max-width: 20rem; }\n.cat-nav2__search input { width: 100%; padding: 0.45rem 0.9rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: 999px; font: inherit; }\n.cat-nav2__user { position: relative; }\n.cat-nav2__user > button { width: 2.5rem; height: 2.5rem; border: 0; border-radius: 50%; background: var(--cat-color-secondary, #4a5568); color: #fff; font: inherit; font-weight: 700; cursor: pointer; }\n.cat-nav2__user ul { position: absolute; right: 0; top: calc(100% + 6px); z-index: 20; min-width: 10rem; margin: 0; padding: 0.25rem; list-style: none; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-surface, #fff); box-shadow: var(--cat-shadow-md, 0 4px 12px rgb(0 0 0 / 0.12)); }\n.cat-nav2__user a { display: block; padding: 0.45rem 0.7rem; border-radius: var(--cat-radius-sm, 0.25rem); color: inherit; text-decoration: none; }\n.cat-nav2__user a:hover { background: rgb(0 0 0 / 0.07); }\n`,
    js: `document.querySelectorAll('[data-cat-nav-user]').forEach(function (root) {\n  var b = root.querySelector('button');\n  var m = root.querySelector('ul');\n  function set(o) { b.setAttribute('aria-expanded', String(o)); m.hidden = !o; }\n  b.addEventListener('click', function () { set(m.hidden); });\n  document.addEventListener('click', function (e) { if (!root.contains(e.target)) set(false); });\n  root.addEventListener('keydown', function (e) { if (e.key === 'Escape') { set(false); b.focus(); } });\n});\n`
  },
  {
    nome: 'Navbar trasparente che diventa piena',
    descrizione: 'Sopra un hero è trasparente con testo bianco; scorrendo prende lo sfondo e l\'ombra',
    tag: ['navbar', 'hero', 'scroll'],
    html: `<header class="cat-nav-clear" id="cat-nav-clear">\n  <a href="/" class="cat-nav-clear__brand" aria-label="Home">${LOGO}</a>\n  <nav aria-label="Principale"><a href="#">Home</a><a href="#">Servizi</a><a href="#">Contatti</a></nav>\n</header>\n<section class="cat-nav-clear__hero"><h1>Titolo sull'immagine</h1></section>\n<div style="height:120vh;padding:1rem">Scorri per vedere la barra riempirsi.</div>\n`,
    css: `${LOGO_CSS}\n.cat-nav-clear { position: fixed; top: 0; left: 0; right: 0; z-index: 20; display: flex; align-items: center; justify-content: space-between; padding: 0.75rem var(--cat-space-3, 1rem); color: #fff; transition: background 250ms ease, color 250ms ease, box-shadow 250ms ease; }\n.cat-nav-clear .cat-logo { color: currentColor; }\n.cat-nav-clear nav { display: flex; gap: var(--cat-space-3, 1rem); }\n.cat-nav-clear a { color: inherit; text-decoration: none; }\n.cat-nav-clear.is-solid { background: var(--cat-color-surface, #fff); color: var(--cat-color-text, #1c1c1a); box-shadow: var(--cat-shadow-md, 0 4px 12px rgb(0 0 0 / 0.12)); }\n.cat-nav-clear.is-solid .cat-logo { color: var(--cat-color-primary, #2f6f4e); }\n.cat-nav-clear__hero { display: grid; place-items: center; min-height: 60vh; background: linear-gradient(135deg, var(--cat-color-secondary, #4a5568), var(--cat-color-primary, #2f6f4e)); color: #fff; }\n@media (prefers-reduced-motion: reduce) { .cat-nav-clear { transition: none; } }\n`,
    js: `var bar = document.getElementById('cat-nav-clear');\nfunction onScroll() { bar.classList.toggle('is-solid', window.scrollY > 40); }\nwindow.addEventListener('scroll', onScroll, { passive: true });\nonScroll();\n`
  },
  {
    nome: 'Navbar scura con pulsante',
    descrizione: 'Barra scura con link e call to action a destra',
    tag: ['navbar', 'scuro', 'cta'],
    html: `<header class="cat-nav-dark">\n  <a href="/" class="cat-nav-dark__brand" aria-label="Home">${LOGO}</a>\n  <nav aria-label="Principale"><a href="#" aria-current="page">Home</a><a href="#">Funzioni</a><a href="#">Prezzi</a><a href="#">Blog</a></nav>\n  <a class="cat-nav-dark__cta" href="#">Prova gratis</a>\n</header>\n`,
    css: `${LOGO_CSS}\n.cat-nav-dark { display: flex; flex-wrap: wrap; align-items: center; gap: var(--cat-space-2, 0.5rem) var(--cat-space-4, 1.5rem); padding: 0.75rem var(--cat-space-3, 1rem); background: #1c1c1a; color: #f2f2ee; }\n.cat-nav-dark .cat-logo { color: #8ad1a8; }\n.cat-nav-dark nav { display: flex; flex-wrap: wrap; gap: var(--cat-space-3, 1rem); margin-right: auto; }\n.cat-nav-dark nav a { color: #cfcfc8; text-decoration: none; }\n.cat-nav-dark nav a:hover, .cat-nav-dark nav a[aria-current="page"] { color: #fff; }\n.cat-nav-dark__cta { padding: 0.45rem 1.1rem; border-radius: 999px; background: #fff; color: #1c1c1a; text-decoration: none; font-weight: 600; }\n`,
    js: ''
  },
  {
    nome: 'Navbar a due livelli',
    descrizione: 'Striscia sottile in alto (contatti, lingua) e barra principale sotto',
    tag: ['navbar', 'logo', 'utility'],
    html: `<div class="cat-nav-2l">\n  <div class="cat-nav-2l__top"><span>📞 011 000 0000</span><span><a href="#">IT</a> · <a href="#">EN</a></span></div>\n  <header class="cat-nav-2l__main">\n    <a href="/" aria-label="Home">${LOGO}</a>\n    <nav aria-label="Principale"><a href="#">Servizi</a><a href="#">Progetti</a><a href="#">Contatti</a></nav>\n  </header>\n</div>\n`,
    css: `${LOGO_CSS}\n.cat-nav-2l__top { display: flex; flex-wrap: wrap; justify-content: space-between; gap: 0.5rem; padding: 0.3rem var(--cat-space-3, 1rem); background: var(--cat-color-primary, #2f6f4e); color: #fff; font-size: 0.8125rem; }\n.cat-nav-2l__top a { color: inherit; }\n.cat-nav-2l__main { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: var(--cat-space-2, 0.5rem); padding: 0.75rem var(--cat-space-3, 1rem); border-bottom: 1px solid var(--cat-color-border, #d9d9d2); background: var(--cat-color-surface, #fff); }\n.cat-nav-2l__main nav { display: flex; gap: var(--cat-space-3, 1rem); }\n.cat-nav-2l__main nav a { color: inherit; text-decoration: none; }\n`,
    js: ''
  },
  {
    nome: 'Navbar laterale (sidebar) comprimibile',
    descrizione: 'Barra verticale con icone che si allarga e restringe con un pulsante',
    tag: ['navbar', 'sidebar', 'app'],
    html: `<div class="cat-side-wrap">\n  <aside class="cat-sidenav" id="cat-sidenav" aria-label="Navigazione">\n    <button type="button" class="cat-sidenav__toggle" aria-expanded="true" aria-controls="cat-sidenav" aria-label="Comprimi la barra">☰</button>\n    <nav>\n      <a href="#" aria-current="page"><span aria-hidden="true">🏠</span><b>Home</b></a>\n      <a href="#"><span aria-hidden="true">📊</span><b>Statistiche</b></a>\n      <a href="#"><span aria-hidden="true">👥</span><b>Clienti</b></a>\n      <a href="#"><span aria-hidden="true">⚙️</span><b>Impostazioni</b></a>\n    </nav>\n  </aside>\n  <main class="cat-side-wrap__main">Contenuto</main>\n</div>\n`,
    css: `.cat-side-wrap { display: flex; min-height: 18rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-lg, 0.75rem); overflow: hidden; }\n.cat-sidenav { flex: 0 0 13rem; padding: var(--cat-space-2, 0.5rem); border-right: 1px solid var(--cat-color-border, #d9d9d2); background: var(--cat-color-surface, #fff); transition: flex-basis 250ms ease; overflow: hidden; }\n.cat-sidenav.is-collapsed { flex-basis: 4rem; }\n.cat-sidenav__toggle { width: 2.5rem; height: 2.5rem; margin-bottom: var(--cat-space-2, 0.5rem); border: 0; border-radius: var(--cat-radius-md, 0.5rem); background: none; font-size: 1.25rem; cursor: pointer; }\n.cat-sidenav nav { display: grid; gap: 0.25rem; }\n.cat-sidenav a { display: flex; align-items: center; gap: 0.75rem; padding: 0.5rem 0.6rem; border-radius: var(--cat-radius-md, 0.5rem); color: inherit; text-decoration: none; white-space: nowrap; }\n.cat-sidenav a:hover { background: rgb(0 0 0 / 0.06); }\n.cat-sidenav a[aria-current="page"] { background: var(--cat-color-primary, #2f6f4e); color: #fff; }\n.cat-sidenav.is-collapsed b { display: none; }\n.cat-side-wrap__main { flex: 1; padding: var(--cat-space-3, 1rem); }\n@media (prefers-reduced-motion: reduce) { .cat-sidenav { transition: none; } }\n`,
    js: `var side = document.getElementById('cat-sidenav');\nvar tog = side.querySelector('.cat-sidenav__toggle');\ntog.addEventListener('click', function () {\n  var c = side.classList.toggle('is-collapsed');\n  tog.setAttribute('aria-expanded', String(!c));\n  tog.setAttribute('aria-label', c ? 'Espandi la barra' : 'Comprimi la barra');\n});\n`
  },
  {
    nome: 'Navbar con menu off-canvas su mobile',
    descrizione: 'Link in riga su desktop; sotto 768 px il pulsante apre un pannello laterale (il classico navbar + offcanvas)',
    tag: ['navbar', 'offcanvas', 'mobile', 'logo'],
    html: `<header class="cat-nav-oc">\n  <a href="/" aria-label="Home">${LOGO}</a>\n  <nav class="cat-nav-oc__links" aria-label="Principale"><a href="#">Home</a><a href="#">Servizi</a><a href="#">Contatti</a></nav>\n  <button type="button" class="cat-nav-oc__open" aria-label="Apri il menu" aria-expanded="false" aria-controls="cat-nav-oc-panel">☰</button>\n</header>\n<div class="cat-nav-oc__backdrop" hidden></div>\n<aside id="cat-nav-oc-panel" class="cat-nav-oc__panel" role="dialog" aria-modal="true" aria-label="Menu" tabindex="-1">\n  <button type="button" class="cat-nav-oc__close" aria-label="Chiudi">×</button>\n  <nav aria-label="Menu mobile"><a href="#">Home</a><a href="#">Servizi</a><a href="#">Contatti</a></nav>\n</aside>\n`,
    css: `${LOGO_CSS}\n.cat-nav-oc { display: flex; align-items: center; justify-content: space-between; padding: 0.6rem var(--cat-space-3, 1rem); border-bottom: 1px solid var(--cat-color-border, #d9d9d2); background: var(--cat-color-surface, #fff); }\n.cat-nav-oc__links { display: flex; gap: var(--cat-space-3, 1rem); }\n.cat-nav-oc a { color: inherit; text-decoration: none; }\n.cat-nav-oc__open, .cat-nav-oc__close { width: 2.5rem; height: 2.5rem; border: 0; border-radius: 50%; background: none; color: inherit; font-size: 1.4rem; cursor: pointer; }\n.cat-nav-oc__open { display: none; }\n.cat-nav-oc__backdrop { position: fixed; inset: 0; z-index: 40; background: rgb(0 0 0 / 0.5); }\n.cat-nav-oc__panel { position: fixed; top: 0; bottom: 0; right: 0; z-index: 50; width: min(18rem, 85vw); padding: var(--cat-space-3, 1rem); background: var(--cat-color-surface, #fff); transform: translateX(100%); visibility: hidden; transition: transform 300ms ease, visibility 0s linear 300ms; }\n.cat-nav-oc__panel.is-open { transform: none; visibility: visible; transition-delay: 0s; }\n.cat-nav-oc__panel nav { display: grid; gap: 0.25rem; margin-top: var(--cat-space-3, 1rem); }\n.cat-nav-oc__panel nav a { display: block; padding: 0.7rem; border-radius: var(--cat-radius-md, 0.5rem); color: inherit; text-decoration: none; font-size: 1.125rem; }\n@media (max-width: 767.98px) {\n  .cat-nav-oc__links { display: none; }\n  .cat-nav-oc__open { display: block; }\n}\n@media (min-width: 768px) {\n  .cat-nav-oc__panel, .cat-nav-oc__backdrop { display: none; }\n}\n@media (prefers-reduced-motion: reduce) { .cat-nav-oc__panel { transition: none; } }\n`,
    js: `(function () {\n  var open = document.querySelector('.cat-nav-oc__open');\n  var panel = document.getElementById('cat-nav-oc-panel');\n  var back = document.querySelector('.cat-nav-oc__backdrop');\n  var close = panel.querySelector('.cat-nav-oc__close');\n  function set(o) {\n    panel.classList.toggle('is-open', o);\n    back.hidden = !o;\n    open.setAttribute('aria-expanded', String(o));\n    document.body.style.overflow = o ? 'hidden' : '';\n    (o ? close : open).focus();\n  }\n  open.addEventListener('click', function () { set(true); });\n  close.addEventListener('click', function () { set(false); });\n  back.addEventListener('click', function () { set(false); });\n  panel.addEventListener('keydown', function (e) { if (e.key === 'Escape') set(false); });\n})();\n`
  }
];
