'use strict';

/* Componenti v4: smartphone e tablet (app bar, tab bar, bottom sheet, mockup, split view…). */

module.exports = [
  {
    nome: 'Mobile: barra delle schede in basso (tab bar)',
    descrizione: 'Navigazione fissa in basso con icone ed etichette, rispetta la safe area dell\'iPhone',
    tag: ['mobile', 'smartphone', 'navigazione', 'tab-bar'],
    html: `<div class="cat-phone-demo">\n  <main class="cat-phone-demo__screen"><h1>Home</h1><p>Contenuto dell'app.</p></main>\n  <nav class="cat-tabbar" aria-label="Sezioni">\n    <a href="#" aria-current="page"><span aria-hidden="true">🏠</span>Home</a>\n    <a href="#"><span aria-hidden="true">🔍</span>Cerca</a>\n    <a href="#"><span aria-hidden="true">❤️</span>Preferiti</a>\n    <a href="#"><span aria-hidden="true">👤</span>Profilo</a>\n  </nav>\n</div>\n`,
    css: `.cat-phone-demo { position: relative; display: flex; flex-direction: column; width: min(100%, 24rem); height: 30rem; margin-inline: auto; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: 1.5rem; overflow: hidden; background: var(--cat-color-bg, #fafaf7); }\n.cat-phone-demo__screen { flex: 1; padding: var(--cat-space-3, 1rem); overflow-y: auto; }\n.cat-tabbar { display: flex; padding-bottom: env(safe-area-inset-bottom); border-top: 1px solid var(--cat-color-border, #d9d9d2); background: var(--cat-color-surface, #fff); }\n.cat-tabbar a { flex: 1; display: grid; justify-items: center; gap: 2px; padding: 0.5rem 0.25rem; color: var(--cat-color-text-muted, #5c5c57); font-size: 0.6875rem; text-decoration: none; }\n.cat-tabbar a span { font-size: 1.35rem; line-height: 1; }\n.cat-tabbar a[aria-current="page"] { color: var(--cat-color-primary, #2f6f4e); font-weight: 700; }\n.cat-tabbar a:focus-visible { outline: 3px solid var(--cat-color-accent, #d97706); outline-offset: -3px; }\n`,
    js: ''
  },
  {
    nome: 'Mobile: barra in alto (app bar)',
    descrizione: 'Titolo centrato con pulsante indietro e azione; resta fissa e rispetta la tacca (safe area)',
    tag: ['mobile', 'smartphone', 'header', 'app-bar'],
    html: `<header class="cat-appbar">\n  <button type="button" class="cat-appbar__btn" aria-label="Indietro">‹</button>\n  <h1 class="cat-appbar__title">Titolo pagina</h1>\n  <button type="button" class="cat-appbar__btn" aria-label="Altre azioni">⋯</button>\n</header>\n`,
    css: `.cat-appbar { position: sticky; top: 0; z-index: 10; display: grid; grid-template-columns: 3rem 1fr 3rem; align-items: center; min-height: 3.5rem; padding-top: env(safe-area-inset-top); border-bottom: 1px solid var(--cat-color-border, #d9d9d2); background: var(--cat-color-surface, #fff); }\n.cat-appbar__title { margin: 0; overflow: hidden; font-size: 1.0625rem; text-align: center; text-overflow: ellipsis; white-space: nowrap; }\n.cat-appbar__btn { width: 3rem; height: 3rem; border: 0; background: none; color: inherit; font-size: 1.6rem; line-height: 1; cursor: pointer; }\n`,
    js: ''
  },
  {
    nome: 'Mobile: pulsante flottante (FAB) con azioni',
    descrizione: 'Cerchio in basso a destra che apre 3 azioni a ventaglio verso l\'alto',
    tag: ['mobile', 'fab', 'smartphone'],
    html: `<div class="cat-fab" data-cat-fab>\n  <ul class="cat-fab__actions" hidden>\n    <li><button type="button" aria-label="Scatta una foto">📷</button></li>\n    <li><button type="button" aria-label="Scrivi una nota">✏️</button></li>\n    <li><button type="button" aria-label="Allega un file">📎</button></li>\n  </ul>\n  <button type="button" class="cat-fab__main" aria-expanded="false" aria-label="Azioni rapide">+</button>\n</div>\n`,
    css: `.cat-fab { position: fixed; right: max(1rem, env(safe-area-inset-right)); bottom: max(1rem, env(safe-area-inset-bottom)); display: grid; justify-items: center; gap: 0.75rem; }\n.cat-fab button { width: 3rem; height: 3rem; border: 0; border-radius: 50%; background: var(--cat-color-surface, #fff); box-shadow: var(--cat-shadow-md, 0 4px 12px rgb(0 0 0 / 0.12)); font-size: 1.25rem; cursor: pointer; }\n.cat-fab .cat-fab__main { width: 3.5rem; height: 3.5rem; background: var(--cat-color-primary, #2f6f4e); color: #fff; font-size: 1.75rem; transition: transform 200ms ease; }\n.cat-fab .cat-fab__main[aria-expanded="true"] { transform: rotate(45deg); }\n.cat-fab__actions { display: grid; gap: 0.6rem; margin: 0; padding: 0; list-style: none; }\n@media (prefers-reduced-motion: reduce) { .cat-fab .cat-fab__main { transition: none; } }\n`,
    js: `document.querySelectorAll('[data-cat-fab]').forEach(function (root) {\n  var main = root.querySelector('.cat-fab__main');\n  var list = root.querySelector('.cat-fab__actions');\n  function set(o) { main.setAttribute('aria-expanded', String(o)); list.hidden = !o; }\n  main.addEventListener('click', function () { set(list.hidden); });\n  document.addEventListener('click', function (e) { if (!root.contains(e.target)) set(false); });\n  root.addEventListener('keydown', function (e) { if (e.key === 'Escape') { set(false); main.focus(); } });\n});\n`
  },
  {
    nome: 'Mobile: bottom sheet',
    descrizione: 'Pannello che sale dal basso con maniglia; si chiude con Esc, tocco fuori o il pulsante',
    tag: ['mobile', 'bottom-sheet', 'dialog'],
    html: `<button type="button" data-cat-sheet-open="#cat-sheet">Apri il foglio</button>\n<dialog id="cat-sheet" class="cat-sheet" aria-labelledby="cat-sheet-title">\n  <div class="cat-sheet__handle" aria-hidden="true"></div>\n  <h2 id="cat-sheet-title">Condividi</h2>\n  <ul class="cat-sheet__list">\n    <li><button type="button">Copia il link</button></li>\n    <li><button type="button">Invia per email</button></li>\n    <li><button type="button" data-cat-sheet-close>Annulla</button></li>\n  </ul>\n</dialog>\n`,
    css: `.cat-sheet { position: fixed; inset: auto 0 0 0; width: 100%; max-width: 32rem; max-height: 80vh; margin: 0 auto; padding: 0.5rem var(--cat-space-3, 1rem) calc(var(--cat-space-3, 1rem) + env(safe-area-inset-bottom)); border: 0; border-radius: 1.25rem 1.25rem 0 0; background: var(--cat-color-surface, #fff); }\n.cat-sheet[open] { animation: cat-sheet-in 280ms ease-out; }\n.cat-sheet::backdrop { background: rgb(0 0 0 / 0.5); }\n.cat-sheet__handle { width: 2.5rem; height: 4px; margin: 0 auto 0.75rem; border-radius: 2px; background: var(--cat-color-border, #d9d9d2); }\n.cat-sheet h2 { margin: 0 0 0.5rem; font-size: 1.125rem; }\n.cat-sheet__list { display: grid; gap: 0.25rem; margin: 0; padding: 0; list-style: none; }\n.cat-sheet__list button { width: 100%; padding: 0.8rem; border: 0; border-radius: var(--cat-radius-md, 0.5rem); background: rgb(0 0 0 / 0.05); color: inherit; font: inherit; text-align: left; cursor: pointer; }\n@keyframes cat-sheet-in { from { transform: translateY(100%); } to { transform: none; } }\n@media (prefers-reduced-motion: reduce) { .cat-sheet[open] { animation: none; } }\n`,
    js: `document.querySelectorAll('[data-cat-sheet-open]').forEach(function (b) {\n  var d = document.querySelector(b.getAttribute('data-cat-sheet-open'));\n  if (!d) return;\n  b.addEventListener('click', function () { d.showModal(); });\n  d.querySelectorAll('[data-cat-sheet-close]').forEach(function (c) { c.addEventListener('click', function () { d.close(); }); });\n  d.addEventListener('click', function (e) { if (e.target === d) d.close(); });\n});\n`
  },
  {
    nome: 'Mobile: menu a tutto schermo',
    descrizione: 'Pulsante in alto che apre un menu che copre lo schermo, con link grandi da toccare',
    tag: ['mobile', 'menu', 'overlay', 'smartphone'],
    html: `<button type="button" class="cat-fs-open" aria-haspopup="dialog" aria-controls="cat-fs-menu">Menu</button>\n<dialog id="cat-fs-menu" class="cat-fs-menu" aria-label="Menu">\n  <button type="button" class="cat-fs-menu__close" aria-label="Chiudi il menu">×</button>\n  <nav aria-label="Principale"><a href="#">Home</a><a href="#">Servizi</a><a href="#">Chi siamo</a><a href="#">Contatti</a></nav>\n</dialog>\n`,
    css: `.cat-fs-open { padding: 0.55rem 1.2rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: 999px; background: var(--cat-color-surface, #fff); color: inherit; font: inherit; cursor: pointer; }\n.cat-fs-menu { width: 100%; max-width: none; height: 100%; max-height: none; margin: 0; padding: var(--cat-space-5, 3rem) var(--cat-space-4, 1.5rem); border: 0; background: var(--cat-color-primary, #2f6f4e); color: #fff; }\n.cat-fs-menu[open] { animation: cat-fs-in 250ms ease-out; }\n.cat-fs-menu nav { display: grid; gap: 0.25rem; }\n.cat-fs-menu nav a { padding: 0.6rem 0; color: inherit; font-size: 2rem; font-weight: 700; text-decoration: none; }\n.cat-fs-menu__close { position: absolute; top: 0.75rem; right: 0.75rem; width: 3rem; height: 3rem; border: 0; background: none; color: inherit; font-size: 2rem; cursor: pointer; }\n@keyframes cat-fs-in { from { opacity: 0; transform: scale(1.03); } to { opacity: 1; transform: none; } }\n@media (prefers-reduced-motion: reduce) { .cat-fs-menu[open] { animation: none; } }\n`,
    js: `var fsBtn = document.querySelector('.cat-fs-open');\nvar fsDlg = document.getElementById('cat-fs-menu');\nfsBtn.addEventListener('click', function () { fsDlg.showModal(); });\nfsDlg.querySelector('.cat-fs-menu__close').addEventListener('click', function () { fsDlg.close(); });\n`
  },
  {
    nome: 'Mobile: barra di azione fissa in basso',
    descrizione: 'Prezzo e pulsante «Acquista» sempre visibili sotto la pagina (sticky bottom CTA)',
    tag: ['mobile', 'cta', 'sticky', 'shop'],
    html: `<div style="min-height:60vh;padding:1rem">Contenuto della pagina del prodotto…</div>\n<div class="cat-buybar">\n  <div><small>Totale</small><strong>39,00 €</strong></div>\n  <button type="button">Acquista ora</button>\n</div>\n`,
    css: `.cat-buybar { position: sticky; bottom: 0; z-index: 10; display: flex; align-items: center; justify-content: space-between; gap: var(--cat-space-3, 1rem); padding: 0.75rem var(--cat-space-3, 1rem) calc(0.75rem + env(safe-area-inset-bottom)); border-top: 1px solid var(--cat-color-border, #d9d9d2); background: var(--cat-color-surface, #fff); }\n.cat-buybar small { display: block; color: var(--cat-color-text-muted, #5c5c57); }\n.cat-buybar strong { font-size: 1.25rem; }\n.cat-buybar button { flex: 0 0 auto; min-height: 2.75rem; padding: 0 1.5rem; border: 0; border-radius: 999px; background: var(--cat-color-primary, #2f6f4e); color: #fff; font: inherit; font-weight: 700; cursor: pointer; }\n`,
    js: ''
  },
  {
    nome: 'Mobile: elenco impostazioni (stile iOS)',
    descrizione: 'Righe con icona, testo, valore e freccia, raggruppate in riquadri arrotondati',
    tag: ['mobile', 'lista', 'impostazioni'],
    html: `<ul class="cat-settings" aria-label="Impostazioni">\n  <li><a href="#"><span aria-hidden="true">🔔</span><b>Notifiche</b><small>Attive</small></a></li>\n  <li><a href="#"><span aria-hidden="true">🌙</span><b>Aspetto</b><small>Automatico</small></a></li>\n  <li><a href="#"><span aria-hidden="true">🔒</span><b>Privacy</b></a></li>\n</ul>\n`,
    css: `.cat-settings { margin: 0; padding: 0; list-style: none; overflow: hidden; border-radius: var(--cat-radius-lg, 0.75rem); background: var(--cat-color-surface, #fff); box-shadow: inset 0 0 0 1px var(--cat-color-border, #d9d9d2); }\n.cat-settings li + li { border-top: 1px solid var(--cat-color-border, #d9d9d2); }\n.cat-settings a { display: flex; align-items: center; gap: 0.75rem; min-height: 3rem; padding: 0.4rem var(--cat-space-3, 1rem); color: inherit; text-decoration: none; }\n.cat-settings a::after { content: "›"; color: var(--cat-color-text-muted, #5c5c57); font-size: 1.4rem; }\n.cat-settings b { flex: 1; font-weight: 500; }\n.cat-settings small { color: var(--cat-color-text-muted, #5c5c57); }\n.cat-settings a:active { background: rgb(0 0 0 / 0.06); }\n`,
    js: ''
  },
  {
    nome: 'Mobile: bolle di chat',
    descrizione: 'Messaggi ricevuti a sinistra e inviati a destra, con orario',
    tag: ['mobile', 'chat'],
    html: `<ol class="cat-chat" aria-label="Conversazione">\n  <li class="cat-chat__in">Ciao! Come va?<time>10:02</time></li>\n  <li class="cat-chat__out">Tutto bene, grazie. Ci sentiamo domani?<time>10:03</time></li>\n  <li class="cat-chat__in">Perfetto 👍<time>10:03</time></li>\n</ol>\n`,
    css: `.cat-chat { display: flex; flex-direction: column; gap: 0.4rem; margin: 0; padding: var(--cat-space-3, 1rem); list-style: none; }\n.cat-chat li { max-width: 78%; padding: 0.55rem 0.8rem; border-radius: 1.1rem; }\n.cat-chat time { display: block; margin-top: 0.15rem; font-size: 0.6875rem; opacity: 0.7; }\n.cat-chat__in { align-self: flex-start; border-bottom-left-radius: 0.3rem; background: rgb(0 0 0 / 0.07); }\n.cat-chat__out { align-self: flex-end; border-bottom-right-radius: 0.3rem; background: var(--cat-color-primary, #2f6f4e); color: #fff; text-align: right; }\n`,
    js: ''
  },
  {
    nome: 'Mobile: storie (cerchi scorrevoli)',
    descrizione: 'Riga di avatar con anello colorato che scorre in orizzontale con il dito',
    tag: ['mobile', 'storie', 'scroll'],
    html: `<ul class="cat-stories" aria-label="Storie">\n  <li><a href="#"><span class="cat-stories__ring"><span class="cat-stories__avatar">AB</span></span>Anna</a></li>\n  <li><a href="#"><span class="cat-stories__ring"><span class="cat-stories__avatar">LR</span></span>Luca</a></li>\n  <li><a href="#"><span class="cat-stories__ring"><span class="cat-stories__avatar">SV</span></span>Sara</a></li>\n  <li><a href="#"><span class="cat-stories__ring"><span class="cat-stories__avatar">MN</span></span>Marco</a></li>\n  <li><a href="#"><span class="cat-stories__ring"><span class="cat-stories__avatar">GP</span></span>Giulia</a></li>\n  <li><a href="#"><span class="cat-stories__ring"><span class="cat-stories__avatar">FT</span></span>Franco</a></li>\n</ul>\n`,
    css: `.cat-stories { display: flex; gap: 0.9rem; margin: 0; padding: 0.5rem var(--cat-space-3, 1rem); overflow-x: auto; list-style: none; scroll-snap-type: x proximity; scrollbar-width: none; }\n.cat-stories li { flex: 0 0 auto; scroll-snap-align: start; }\n.cat-stories a { display: grid; justify-items: center; gap: 0.25rem; color: inherit; font-size: 0.75rem; text-decoration: none; }\n.cat-stories__ring { display: grid; place-items: center; width: 4.25rem; height: 4.25rem; border-radius: 50%; background: conic-gradient(var(--cat-color-accent, #d97706), var(--cat-color-primary, #2f6f4e), var(--cat-color-accent, #d97706)); }\n.cat-stories__avatar { display: grid; place-items: center; width: 3.65rem; height: 3.65rem; border: 3px solid var(--cat-color-surface, #fff); border-radius: 50%; background: var(--cat-color-secondary, #4a5568); color: #fff; font-weight: 700; }\n`,
    js: ''
  },
  {
    nome: 'Mobile: onboarding a schermate',
    descrizione: 'Schermate che scorrono con scroll-snap e indicatori, con pulsante «Salta»',
    tag: ['mobile', 'onboarding', 'scroll-snap'],
    html: `<section class="cat-onb" aria-label="Introduzione">\n  <div class="cat-onb__track" id="cat-onb-track">\n    <article class="cat-onb__slide"><div aria-hidden="true">📚</div><h2>Tutto in un posto</h2><p>Raccogli i tuoi componenti.</p></article>\n    <article class="cat-onb__slide"><div aria-hidden="true">🔍</div><h2>Trova al volo</h2><p>Cerca con Ctrl+K.</p></article>\n    <article class="cat-onb__slide"><div aria-hidden="true">🚀</div><h2>Copia e incolla</h2><p>Pronto per il tuo sito.</p></article>\n  </div>\n  <div class="cat-onb__foot"><button type="button" class="cat-onb__skip">Salta</button><span class="cat-onb__dots" aria-hidden="true"></span></div>\n</section>\n`,
    css: `.cat-onb { width: min(100%, 24rem); margin-inline: auto; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: 1.5rem; overflow: hidden; background: var(--cat-color-surface, #fff); }\n.cat-onb__track { display: flex; overflow-x: auto; scroll-snap-type: x mandatory; scrollbar-width: none; }\n.cat-onb__slide { flex: 0 0 100%; padding: var(--cat-space-5, 3rem) var(--cat-space-4, 1.5rem); text-align: center; scroll-snap-align: center; }\n.cat-onb__slide div { font-size: 4rem; }\n.cat-onb__foot { display: flex; align-items: center; justify-content: space-between; padding: 0.75rem var(--cat-space-3, 1rem); }\n.cat-onb__skip { border: 0; background: none; color: var(--cat-color-primary, #2f6f4e); font: inherit; cursor: pointer; }\n.cat-onb__dots { display: flex; gap: 0.4rem; }\n.cat-onb__dots i { width: 0.55rem; height: 0.55rem; border-radius: 50%; background: var(--cat-color-border, #d9d9d2); }\n.cat-onb__dots i.is-on { background: var(--cat-color-primary, #2f6f4e); }\n`,
    js: `var onbTrack = document.getElementById('cat-onb-track');\nvar onbDots = document.querySelector('.cat-onb__dots');\nvar onbN = onbTrack.children.length;\nfor (var i = 0; i < onbN; i++) onbDots.appendChild(document.createElement('i'));\nfunction onbSync() {\n  var k = Math.round(onbTrack.scrollLeft / onbTrack.clientWidth);\n  Array.prototype.forEach.call(onbDots.children, function (d, j) { d.classList.toggle('is-on', j === k); });\n}\nonbTrack.addEventListener('scroll', onbSync, { passive: true });\nonbSync();\ndocument.querySelector('.cat-onb__skip').addEventListener('click', function () { onbTrack.scrollTo({ left: onbTrack.scrollWidth, behavior: 'smooth' }); });\n`
  },
  {
    nome: 'Smartphone: cornice (mockup) per screenshot',
    descrizione: 'Cornice di telefono in solo CSS con tacca e barra home; ci metti dentro schermate o un\'immagine',
    tag: ['smartphone', 'mockup', 'cornice', 'device'],
    html: `<div class="cat-device-phone" role="img" aria-label="Anteprima su smartphone">\n  <div class="cat-device-phone__screen">\n    <div class="cat-device-phone__content"><p>Qui la tua schermata<br><small>(un’immagine con object-fit: cover)</small></p></div>\n  </div>\n</div>\n`,
    css: `.cat-device-phone { position: relative; width: min(100%, 16rem); aspect-ratio: 9 / 19; margin-inline: auto; padding: 0.7rem; border-radius: 2.4rem; background: #1c1c1a; box-shadow: 0 0 0 2px #3a3a36, var(--cat-shadow-md, 0 4px 12px rgb(0 0 0 / 0.12)); }\n.cat-device-phone::before { content: ""; position: absolute; top: 1.1rem; left: 50%; z-index: 2; width: 28%; height: 1.1rem; transform: translateX(-50%); border-radius: 999px; background: #000; }\n.cat-device-phone::after { content: ""; position: absolute; bottom: 1.1rem; left: 50%; z-index: 2; width: 34%; height: 4px; transform: translateX(-50%); border-radius: 2px; background: rgb(255 255 255 / 0.7); }\n.cat-device-phone__screen { width: 100%; height: 100%; overflow: hidden; border-radius: 1.8rem; background: var(--cat-color-surface, #fff); }\n.cat-device-phone__content { display: grid; place-items: center; width: 100%; height: 100%; padding: 2rem 1rem; background: linear-gradient(160deg, #e9f2ec, #fff); color: var(--cat-color-text, #1c1c1a); text-align: center; }\n.cat-device-phone__content img { width: 100%; height: 100%; object-fit: cover; }\n`,
    js: ''
  },
  {
    nome: 'Tablet: cornice (mockup) per screenshot',
    descrizione: 'Cornice di tablet in solo CSS, orizzontale, con telecamera',
    tag: ['tablet', 'mockup', 'cornice', 'device'],
    html: `<div class="cat-device-tablet" role="img" aria-label="Anteprima su tablet">\n  <div class="cat-device-tablet__screen">\n    <div class="cat-device-tablet__content">Qui la tua schermata</div>\n  </div>\n</div>\n`,
    css: `.cat-device-tablet { position: relative; width: min(100%, 34rem); aspect-ratio: 4 / 3; margin-inline: auto; padding: 1.1rem; border-radius: 1.6rem; background: #1c1c1a; box-shadow: 0 0 0 2px #3a3a36, var(--cat-shadow-md, 0 4px 12px rgb(0 0 0 / 0.12)); }\n.cat-device-tablet::before { content: ""; position: absolute; top: 50%; left: 0.45rem; width: 0.4rem; height: 0.4rem; transform: translateY(-50%); border-radius: 50%; background: #3a3a36; }\n.cat-device-tablet__screen { width: 100%; height: 100%; overflow: hidden; border-radius: 0.6rem; background: var(--cat-color-surface, #fff); }\n.cat-device-tablet__content { display: grid; place-items: center; width: 100%; height: 100%; background: linear-gradient(160deg, #e9f2ec, #fff); color: var(--cat-color-text, #1c1c1a); }\n.cat-device-tablet__content img { width: 100%; height: 100%; object-fit: cover; }\n`,
    js: ''
  },
  {
    nome: 'Tablet: vista divisa (elenco + dettaglio)',
    descrizione: 'Master-detail: elenco a sinistra e dettaglio a destra; sotto 768 px si vede una colonna alla volta',
    tag: ['tablet', 'split-view', 'layout', 'responsive'],
    html: `<div class="cat-split-view" id="cat-sv">\n  <nav class="cat-split-view__list" aria-label="Messaggi">\n    <button type="button" aria-current="true" data-msg="Anna: ciao, ci sei?">Anna<small>ciao, ci sei?</small></button>\n    <button type="button" data-msg="Luca: ti mando i file">Luca<small>ti mando i file</small></button>\n    <button type="button" data-msg="Sara: perfetto, grazie">Sara<small>perfetto, grazie</small></button>\n  </nav>\n  <section class="cat-split-view__detail" aria-live="polite">\n    <button type="button" class="cat-split-view__back">‹ Indietro</button>\n    <p id="cat-sv-text">Anna: ciao, ci sei?</p>\n  </section>\n</div>\n`,
    css: `.cat-split-view { display: grid; grid-template-columns: minmax(12rem, 18rem) 1fr; min-height: 16rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-lg, 0.75rem); overflow: hidden; background: var(--cat-color-surface, #fff); }\n.cat-split-view__list { display: grid; align-content: start; border-right: 1px solid var(--cat-color-border, #d9d9d2); }\n.cat-split-view__list button { display: grid; gap: 0.1rem; padding: 0.8rem var(--cat-space-3, 1rem); border: 0; border-bottom: 1px solid var(--cat-color-border, #d9d9d2); background: none; color: inherit; font: inherit; font-weight: 600; text-align: left; cursor: pointer; }\n.cat-split-view__list small { color: var(--cat-color-text-muted, #5c5c57); font-weight: 400; }\n.cat-split-view__list button[aria-current="true"] { background: rgb(47 111 78 / 0.12); }\n.cat-split-view__detail { padding: var(--cat-space-3, 1rem); }\n.cat-split-view__back { display: none; margin-bottom: 0.5rem; border: 0; background: none; color: var(--cat-color-primary, #2f6f4e); font: inherit; cursor: pointer; }\n@media (max-width: 767.98px) {\n  .cat-split-view { grid-template-columns: 1fr; }\n  .cat-split-view__detail { display: none; }\n  .cat-split-view.is-detail .cat-split-view__list { display: none; }\n  .cat-split-view.is-detail .cat-split-view__detail { display: block; }\n  .cat-split-view__back { display: inline-block; }\n}\n`,
    js: `var sv = document.getElementById('cat-sv');\nvar svText = document.getElementById('cat-sv-text');\nsv.querySelectorAll('.cat-split-view__list button').forEach(function (b) {\n  b.addEventListener('click', function () {\n    sv.querySelectorAll('.cat-split-view__list button').forEach(function (x) { x.setAttribute('aria-current', String(x === b)); });\n    svText.textContent = b.getAttribute('data-msg');\n    sv.classList.add('is-detail');\n  });\n});\nsv.querySelector('.cat-split-view__back').addEventListener('click', function () { sv.classList.remove('is-detail'); });\n`
  },
  {
    nome: 'Tablet: barra di navigazione laterale stretta (rail)',
    descrizione: 'Colonna sottile con icone ed etichette sotto, tipica dei tablet; in basso su telefono',
    tag: ['tablet', 'navigazione', 'rail', 'responsive'],
    html: `<div class="cat-rail-wrap">\n  <nav class="cat-rail" aria-label="Sezioni">\n    <a href="#" aria-current="page"><span aria-hidden="true">🏠</span>Home</a>\n    <a href="#"><span aria-hidden="true">📁</span>File</a>\n    <a href="#"><span aria-hidden="true">💬</span>Chat</a>\n    <a href="#"><span aria-hidden="true">⚙️</span>Altro</a>\n  </nav>\n  <main class="cat-rail-wrap__main">Contenuto</main>\n</div>\n`,
    css: `.cat-rail-wrap { display: flex; min-height: 18rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-lg, 0.75rem); overflow: hidden; }\n.cat-rail { display: flex; flex-direction: column; gap: 0.5rem; flex: 0 0 4.75rem; padding: 0.75rem 0.25rem; border-right: 1px solid var(--cat-color-border, #d9d9d2); background: var(--cat-color-surface, #fff); }\n.cat-rail a { display: grid; justify-items: center; gap: 2px; padding: 0.4rem 0; border-radius: var(--cat-radius-md, 0.5rem); color: var(--cat-color-text-muted, #5c5c57); font-size: 0.6875rem; text-decoration: none; }\n.cat-rail a span { font-size: 1.4rem; }\n.cat-rail a[aria-current="page"] { background: rgb(47 111 78 / 0.14); color: var(--cat-color-primary, #2f6f4e); font-weight: 700; }\n.cat-rail-wrap__main { flex: 1; padding: var(--cat-space-3, 1rem); }\n@media (max-width: 575.98px) {\n  .cat-rail-wrap { flex-direction: column-reverse; }\n  .cat-rail { flex-direction: row; flex-basis: auto; border-right: 0; border-top: 1px solid var(--cat-color-border, #d9d9d2); }\n  .cat-rail a { flex: 1; }\n}\n`,
    js: ''
  },
  {
    nome: 'Tablet: posta a tre colonne',
    descrizione: 'Cartelle, elenco e lettura affiancati; si riducono a due e a una colonna sullo schermo più stretto',
    tag: ['tablet', 'layout', 'tre-colonne', 'responsive'],
    html: `<div class="cat-mail">\n  <nav class="cat-mail__folders" aria-label="Cartelle"><a href="#" aria-current="page">Ricevuti</a><a href="#">Inviati</a><a href="#">Bozze</a></nav>\n  <ul class="cat-mail__list" aria-label="Messaggi"><li><b>Anna</b><small>Riunione di domani</small></li><li><b>Luca</b><small>File del progetto</small></li></ul>\n  <article class="cat-mail__read"><h2>Riunione di domani</h2><p>Testo del messaggio selezionato.</p></article>\n</div>\n`,
    css: `.cat-mail { display: grid; grid-template-columns: 10rem 16rem 1fr; min-height: 16rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-lg, 0.75rem); overflow: hidden; background: var(--cat-color-surface, #fff); }\n.cat-mail > * { padding: var(--cat-space-3, 1rem); }\n.cat-mail > * + * { border-left: 1px solid var(--cat-color-border, #d9d9d2); }\n.cat-mail__folders { display: grid; align-content: start; gap: 0.25rem; }\n.cat-mail__folders a { padding: 0.4rem 0.6rem; border-radius: var(--cat-radius-sm, 0.25rem); color: inherit; text-decoration: none; }\n.cat-mail__folders a[aria-current="page"] { background: rgb(47 111 78 / 0.14); font-weight: 700; }\n.cat-mail__list { margin: 0; list-style: none; }\n.cat-mail__list li { display: grid; padding: 0.5rem 0; border-bottom: 1px solid var(--cat-color-border, #d9d9d2); }\n.cat-mail__list small { color: var(--cat-color-text-muted, #5c5c57); }\n@media (max-width: 991.98px) { .cat-mail { grid-template-columns: 9rem 1fr; } .cat-mail__read { display: none; } }\n@media (max-width: 575.98px) { .cat-mail { grid-template-columns: 1fr; } .cat-mail__folders { display: flex; border-bottom: 1px solid var(--cat-color-border, #d9d9d2); } .cat-mail > * + * { border-left: 0; } }\n`,
    js: ''
  },
  {
    nome: 'Mobile: griglia di icone dell\'app (launcher)',
    descrizione: 'Icone tonde con nome in una griglia che si adatta a 3, 4 o 6 per riga',
    tag: ['mobile', 'tablet', 'griglia', 'icone'],
    html: `<ul class="cat-launcher" aria-label="App">\n  <li><a href="#"><span aria-hidden="true">📷</span>Foto</a></li>\n  <li><a href="#"><span aria-hidden="true">🗓️</span>Agenda</a></li>\n  <li><a href="#"><span aria-hidden="true">🎵</span>Musica</a></li>\n  <li><a href="#"><span aria-hidden="true">🗺️</span>Mappe</a></li>\n  <li><a href="#"><span aria-hidden="true">✉️</span>Posta</a></li>\n  <li><a href="#"><span aria-hidden="true">⚙️</span>Impost.</a></li>\n</ul>\n`,
    css: `.cat-launcher { display: grid; grid-template-columns: repeat(auto-fill, minmax(4.5rem, 1fr)); gap: var(--cat-space-3, 1rem); margin: 0; padding: var(--cat-space-3, 1rem); list-style: none; }\n.cat-launcher a { display: grid; justify-items: center; gap: 0.3rem; color: inherit; font-size: 0.75rem; text-decoration: none; }\n.cat-launcher span { display: grid; place-items: center; width: 3.5rem; height: 3.5rem; border-radius: 1rem; background: linear-gradient(145deg, #fff, #e9f2ec); box-shadow: inset 0 0 0 1px var(--cat-color-border, #d9d9d2); font-size: 1.75rem; }\n.cat-launcher a:active span { transform: scale(0.94); }\n`,
    js: ''
  }
];
