'use strict';

/* Interazioni v2: moduli, carosello, drawer, ordinamento, conto alla rovescia. */

module.exports = [
  {
    nome: 'Menu laterale (drawer)',
    descrizione: 'Pannello che scorre da destra con sfondo scuro; Esc e clic fuori lo chiudono',
    tag: ['menu', 'drawer', 'dialog'],
    html: `<button type="button" data-cat-drawer-open="#cat-drawer">Apri il menu</button>\n<dialog id="cat-drawer" class="cat-drawer" aria-label="Menu">\n  <button type="button" data-cat-drawer-close aria-label="Chiudi">×</button>\n  <nav><a href="#">Home</a><a href="#">Servizi</a><a href="#">Contatti</a></nav>\n</dialog>\n`,
    css: `.cat-drawer { position: fixed; inset: 0 0 0 auto; width: min(20rem, 85vw); height: 100%; max-height: none; margin: 0; padding: var(--cat-space-4, 1.5rem); border: 0; background: var(--cat-color-surface, #fff); }\n.cat-drawer[open] { animation: cat-drawer-in 250ms ease-out; }\n.cat-drawer::backdrop { background: rgb(0 0 0 / 0.5); }\n.cat-drawer nav { display: grid; gap: var(--cat-space-2, 0.5rem); margin-top: var(--cat-space-4, 1.5rem); }\n.cat-drawer nav a { color: inherit; font-size: 1.125rem; text-decoration: none; }\n.cat-drawer [data-cat-drawer-close] { position: absolute; top: 0.5rem; right: 0.75rem; border: 0; background: none; font-size: 1.75rem; cursor: pointer; }\n@keyframes cat-drawer-in { from { transform: translateX(100%); } to { transform: none; } }\n@media (prefers-reduced-motion: reduce) { .cat-drawer[open] { animation: none; } }\n`,
    js: `document.querySelectorAll('[data-cat-drawer-open]').forEach(function (b) {\n  var d = document.querySelector(b.getAttribute('data-cat-drawer-open'));\n  if (!d) return;\n  b.addEventListener('click', function () { d.showModal(); });\n  d.querySelectorAll('[data-cat-drawer-close]').forEach(function (c) { c.addEventListener('click', function () { d.close(); }); });\n  d.addEventListener('click', function (e) { if (e.target === d) d.close(); });\n});\n`
  },
  {
    nome: 'Carosello con frecce e puntini',
    descrizione: 'Slide con pulsanti precedente/successivo e indicatori, tastiera inclusa',
    tag: ['carosello', 'galleria', 'aria'],
    html: `<section class="cat-slider" aria-roledescription="carosello" aria-label="Galleria">\n  <div class="cat-slider__track">\n    <div class="cat-slider__slide">Slide 1</div>\n    <div class="cat-slider__slide">Slide 2</div>\n    <div class="cat-slider__slide">Slide 3</div>\n  </div>\n  <button type="button" class="cat-slider__prev" aria-label="Precedente">‹</button>\n  <button type="button" class="cat-slider__next" aria-label="Successiva">›</button>\n  <div class="cat-slider__dots" role="group" aria-label="Scegli slide"></div>\n</section>\n`,
    css: `.cat-slider { position: relative; overflow: hidden; border-radius: var(--cat-radius-lg, 0.75rem); }\n.cat-slider__track { display: flex; transition: transform 350ms ease; }\n.cat-slider__slide { flex: 0 0 100%; display: grid; place-items: center; height: 12rem; background: var(--cat-color-border, #d9d9d2); font-size: 1.5rem; }\n.cat-slider__prev, .cat-slider__next { position: absolute; top: 50%; width: 2.5rem; height: 2.5rem; margin-top: -1.25rem; border: 0; border-radius: 50%; background: rgb(255 255 255 / 0.85); font-size: 1.5rem; cursor: pointer; }\n.cat-slider__prev { left: 0.5rem; }\n.cat-slider__next { right: 0.5rem; }\n.cat-slider__dots { position: absolute; left: 0; right: 0; bottom: 0.5rem; display: flex; justify-content: center; gap: 0.4rem; }\n.cat-slider__dots button { width: 0.7rem; height: 0.7rem; padding: 0; border: 0; border-radius: 50%; background: rgb(0 0 0 / 0.3); cursor: pointer; }\n.cat-slider__dots button[aria-current="true"] { background: var(--cat-color-primary, #2f6f4e); }\n@media (prefers-reduced-motion: reduce) { .cat-slider__track { transition: none; } }\n`,
    js: `document.querySelectorAll('.cat-slider').forEach(function (root) {\n  var track = root.querySelector('.cat-slider__track');\n  var n = track.children.length;\n  var dots = root.querySelector('.cat-slider__dots');\n  var i = 0;\n  function go(k) {\n    i = (k + n) % n;\n    track.style.transform = 'translateX(' + (-100 * i) + '%)';\n    Array.prototype.forEach.call(dots.children, function (d, j) { d.setAttribute('aria-current', String(j === i)); });\n  }\n  for (var k = 0; k < n; k++) {\n    (function (k) {\n      var d = document.createElement('button');\n      d.type = 'button';\n      d.setAttribute('aria-label', 'Slide ' + (k + 1));\n      d.addEventListener('click', function () { go(k); });\n      dots.appendChild(d);\n    })(k);\n  }\n  root.querySelector('.cat-slider__prev').addEventListener('click', function () { go(i - 1); });\n  root.querySelector('.cat-slider__next').addEventListener('click', function () { go(i + 1); });\n  root.addEventListener('keydown', function (e) {\n    if (e.key === 'ArrowLeft') go(i - 1);\n    if (e.key === 'ArrowRight') go(i + 1);\n  });\n  go(0);\n});\n`
  },
  {
    nome: 'Mostra/nascondi password',
    descrizione: 'Pulsante nel campo che alterna password e testo',
    tag: ['form', 'password'],
    html: `<label for="cat-pw">Password</label>\n<div class="cat-pw">\n  <input id="cat-pw" type="password" autocomplete="current-password">\n  <button type="button" aria-controls="cat-pw" aria-pressed="false">Mostra</button>\n</div>\n`,
    css: `.cat-pw { display: flex; max-width: 22rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); }\n.cat-pw input { flex: 1; min-width: 0; padding: 0.55rem 0.7rem; border: 0; outline: 0; background: none; font: inherit; }\n.cat-pw button { padding: 0 0.9rem; border: 0; background: none; color: var(--cat-color-primary, #2f6f4e); font: inherit; cursor: pointer; }\n.cat-pw:focus-within { outline: 3px solid var(--cat-color-accent, #d97706); outline-offset: 1px; }\n`,
    js: `document.querySelectorAll('.cat-pw').forEach(function (box) {\n  var input = box.querySelector('input');\n  var btn = box.querySelector('button');\n  btn.addEventListener('click', function () {\n    var show = input.type === 'password';\n    input.type = show ? 'text' : 'password';\n    btn.textContent = show ? 'Nascondi' : 'Mostra';\n    btn.setAttribute('aria-pressed', String(show));\n  });\n});\n`
  },
  {
    nome: 'Contatore di caratteri',
    descrizione: 'Mostra quanti caratteri restano e diventa rosso al limite',
    tag: ['form', 'textarea'],
    html: `<label for="cat-cc">Messaggio</label>\n<textarea id="cat-cc" rows="3" maxlength="140" data-cat-counter="#cat-cc-out"></textarea>\n<small id="cat-cc-out" aria-live="polite">140 caratteri rimasti</small>\n`,
    css: `textarea[data-cat-counter] { display: block; width: 100%; max-width: 28rem; padding: 0.55rem 0.7rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); font: inherit; }\n#cat-cc-out { color: var(--cat-color-text-muted, #5c5c57); }\n#cat-cc-out.is-low { color: var(--cat-color-error, #b3261e); font-weight: 700; }\n`,
    js: `document.querySelectorAll('[data-cat-counter]').forEach(function (ta) {\n  var out = document.querySelector(ta.getAttribute('data-cat-counter'));\n  var max = ta.maxLength;\n  ta.addEventListener('input', function () {\n    var left = max - ta.value.length;\n    out.textContent = left + ' caratteri rimasti';\n    out.classList.toggle('is-low', left <= 20);\n  });\n});\n`
  },
  {
    nome: 'Tabella ordinabile',
    descrizione: 'Clic sull\'intestazione per ordinare per quella colonna (testo o numeri)',
    tag: ['tabella', 'dati'],
    html: `<table class="cat-sort">\n  <thead><tr><th scope="col" aria-sort="none"><button type="button">Nome</button></th><th scope="col" aria-sort="none"><button type="button">Età</button></th></tr></thead>\n  <tbody>\n    <tr><td>Carla</td><td>31</td></tr>\n    <tr><td>Anna</td><td>27</td></tr>\n    <tr><td>Bruno</td><td>45</td></tr>\n  </tbody>\n</table>\n`,
    css: `.cat-sort { border-collapse: collapse; min-width: 16rem; }\n.cat-sort th, .cat-sort td { padding: 0.5rem 0.9rem; border-bottom: 1px solid var(--cat-color-border, #d9d9d2); text-align: left; }\n.cat-sort th button { padding: 0; border: 0; background: none; color: inherit; font: inherit; font-weight: 700; cursor: pointer; }\n.cat-sort th[aria-sort="ascending"] button::after { content: " ▲"; font-size: 0.7em; }\n.cat-sort th[aria-sort="descending"] button::after { content: " ▼"; font-size: 0.7em; }\n`,
    js: `document.querySelectorAll('.cat-sort').forEach(function (table) {\n  var heads = table.querySelectorAll('th');\n  heads.forEach(function (th, col) {\n    th.querySelector('button').addEventListener('click', function () {\n      var dir = th.getAttribute('aria-sort') === 'ascending' ? 'descending' : 'ascending';\n      heads.forEach(function (h) { h.setAttribute('aria-sort', 'none'); });\n      th.setAttribute('aria-sort', dir);\n      var body = table.tBodies[0];\n      var rows = Array.prototype.slice.call(body.rows);\n      rows.sort(function (a, b) {\n        var x = a.cells[col].textContent.trim();\n        var y = b.cells[col].textContent.trim();\n        var nx = parseFloat(x), ny = parseFloat(y);\n        var r = (!isNaN(nx) && !isNaN(ny)) ? nx - ny : x.localeCompare(y, 'it');\n        return dir === 'ascending' ? r : -r;\n      });\n      rows.forEach(function (r) { body.appendChild(r); });\n    });\n  });\n});\n`
  },
  {
    nome: 'Conto alla rovescia',
    descrizione: 'Giorni, ore, minuti e secondi verso una data',
    tag: ['tempo', 'evento'],
    html: `<div class="cat-countdown" data-cat-countdown="2026-12-31T23:59:59" role="timer" aria-label="Conto alla rovescia">\n  <div><b data-u="d">0</b><small>giorni</small></div>\n  <div><b data-u="h">0</b><small>ore</small></div>\n  <div><b data-u="m">0</b><small>minuti</small></div>\n  <div><b data-u="s">0</b><small>secondi</small></div>\n</div>\n`,
    css: `.cat-countdown { display: flex; flex-wrap: wrap; gap: var(--cat-space-3, 1rem); }\n.cat-countdown div { min-width: 4.5rem; padding: var(--cat-space-2, 0.5rem); border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); text-align: center; }\n.cat-countdown b { display: block; font-size: 1.75rem; font-variant-numeric: tabular-nums; color: var(--cat-color-primary, #2f6f4e); }\n.cat-countdown small { color: var(--cat-color-text-muted, #5c5c57); }\n`,
    js: `document.querySelectorAll('[data-cat-countdown]').forEach(function (el) {\n  var end = new Date(el.getAttribute('data-cat-countdown')).getTime();\n  function tick() {\n    var left = Math.max(0, end - Date.now());\n    var v = { d: Math.floor(left / 864e5), h: Math.floor(left / 36e5) % 24, m: Math.floor(left / 6e4) % 60, s: Math.floor(left / 1e3) % 60 };\n    Object.keys(v).forEach(function (k) { el.querySelector('[data-u="' + k + '"]').textContent = v[k]; });\n  }\n  tick();\n  setInterval(tick, 1000);\n});\n`
  },
  {
    nome: 'Form a più passi',
    descrizione: 'Un modulo diviso in passi con Avanti/Indietro e indicatore',
    tag: ['form', 'passi', 'wizard'],
    html: `<form class="cat-wizard" novalidate>\n  <p class="cat-wizard__step" aria-live="polite">Passo 1 di 3</p>\n  <fieldset data-step><legend>Chi sei</legend><label>Nome<input type="text"></label></fieldset>\n  <fieldset data-step hidden><legend>Contatti</legend><label>Email<input type="email"></label></fieldset>\n  <fieldset data-step hidden><legend>Conferma</legend><p>Controlla e invia.</p></fieldset>\n  <div class="cat-wizard__nav">\n    <button type="button" data-prev>Indietro</button>\n    <button type="button" data-next>Avanti</button>\n  </div>\n</form>\n`,
    css: `.cat-wizard { max-width: 24rem; }\n.cat-wizard fieldset { margin: 0 0 var(--cat-space-3, 1rem); padding: var(--cat-space-3, 1rem); border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); }\n.cat-wizard label { display: grid; gap: 0.25rem; font-weight: 600; }\n.cat-wizard input { padding: 0.5rem 0.7rem; border: 1px solid var(--cat-color-border, #d9d9d2); border-radius: var(--cat-radius-md, 0.5rem); font: inherit; }\n.cat-wizard__step { margin: 0 0 0.5rem; color: var(--cat-color-text-muted, #5c5c57); font-size: 0.875rem; }\n.cat-wizard__nav { display: flex; justify-content: space-between; }\n.cat-wizard__nav button { padding: 0.5rem 1.2rem; border: 0; border-radius: var(--cat-radius-md, 0.5rem); background: var(--cat-color-primary, #2f6f4e); color: #fff; font: inherit; cursor: pointer; }\n.cat-wizard__nav button[disabled] { visibility: hidden; }\n`,
    js: `document.querySelectorAll('.cat-wizard').forEach(function (form) {\n  var steps = form.querySelectorAll('[data-step]');\n  var label = form.querySelector('.cat-wizard__step');\n  var prev = form.querySelector('[data-prev]');\n  var next = form.querySelector('[data-next]');\n  var i = 0;\n  function show() {\n    steps.forEach(function (s, k) { s.hidden = k !== i; });\n    label.textContent = 'Passo ' + (i + 1) + ' di ' + steps.length;\n    prev.disabled = i === 0;\n    next.textContent = i === steps.length - 1 ? 'Invia' : 'Avanti';\n  }\n  prev.addEventListener('click', function () { i = Math.max(0, i - 1); show(); });\n  next.addEventListener('click', function () {\n    if (i < steps.length - 1) { i += 1; show(); } else { form.dispatchEvent(new Event('submit', { cancelable: true })); }\n  });\n  show();\n});\n`
  },
  {
    nome: 'Valutazione cliccabile',
    descrizione: 'Cinque stelle che si scelgono con il mouse o la tastiera (radio nativi)',
    tag: ['form', 'stelle'],
    html: `<fieldset class="cat-rate">\n  <legend>La tua valutazione</legend>\n  <input type="radio" name="cat-rate" id="cat-r5" value="5"><label for="cat-r5" title="5 stelle">★</label>\n  <input type="radio" name="cat-rate" id="cat-r4" value="4"><label for="cat-r4" title="4 stelle">★</label>\n  <input type="radio" name="cat-rate" id="cat-r3" value="3"><label for="cat-r3" title="3 stelle">★</label>\n  <input type="radio" name="cat-rate" id="cat-r2" value="2"><label for="cat-r2" title="2 stelle">★</label>\n  <input type="radio" name="cat-rate" id="cat-r1" value="1"><label for="cat-r1" title="1 stella">★</label>\n</fieldset>\n`,
    css: `.cat-rate { display: inline-flex; flex-direction: row-reverse; justify-content: flex-end; gap: 0.1rem; margin: 0; padding: 0; border: 0; }\n.cat-rate legend { margin-bottom: 0.25rem; font-weight: 600; }\n.cat-rate input { position: absolute; opacity: 0; }\n.cat-rate label { color: var(--cat-color-border, #d9d9d2); font-size: 2rem; line-height: 1; cursor: pointer; }\n.cat-rate input:checked ~ label, .cat-rate label:hover, .cat-rate label:hover ~ label { color: #f5a623; }\n.cat-rate input:focus-visible + label { outline: 3px solid var(--cat-color-accent, #d97706); outline-offset: 2px; }\n`,
    js: ''
  }
];
